config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  get 'welcome/inteligencia_global_ai'
  get 'welcome/sectorial_ai'
  get 'welcome/iot_sectorial'
  get 'welcome/inteligencia_global_iot'
  get 'welcome/bc_sectorial'
  get 'welcome/inteligencia_global_blockchain'


  resources :cities
  resources :companies

    namespace :charts do
      get "company_all"



    end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ActiveRecord::Base
   self.table_name = "octi_cities"

end

app/models/company.rb
class Company < ApplicationRecord
   self.table_name = "octi_companies"





end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController

   def company_all
     render json: Company.group_by_year(:founded_date).count
   end

   #def patents_chart
    # render json: Patent.group_by_year(:fecha).count
   #end
   #def markets_chart
  #   render json: Market.group(:title).sum(:projected_sales)
  # end

   #def markets_sales
  #   render json: Market.group(:title).sum(:score)
  # end




end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def city_params
      params.require(:city).permit(:name)
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = City.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :description, :employee_number, :website, :twitter, :facebook, :linkedin, :contact_email, :phone_number, :investment_received, :sales_value, :assets, :products, :services, :founded_date, :score, :tags, :export_sales, :imports)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
      @companies = Company.all
      
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/_form.html.erb
<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
        <% city.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/companies/index.html.erb
<br>
<br>

 <div id="piechart" style="width: 900px; height: 500px;"></div>
<h1>Companies</h1>



<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.sales_value %></td>
        <td><%= company.founded_date %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_company_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>ObservatorioSql</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
     <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

     <script type="text/javascript">
           google.charts.load('current', {'packages':['corechart']});
           google.charts.setOnLoadCallback(drawChart);

           function drawChart() {

             var data = google.visualization.arrayToDataTable([
               ['Task', 'Hours per Day'],
               ['Work',     11],
               ['Eat',      2],
               ['Commute',  2],
               ['Watch TV', 2],
               ['Sleep',    7]
             ]);

             var options = {
               title: 'My Daily Activities'
             };

             var chart = new google.visualization.PieChart(document.getElementById('piechart'));

             chart.draw(data, options);
           }
         </script>


    

    </head>

   <%= render "partials/navbar" %>
    <body>

      <%= yield %>

      <!-- Chart JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js" integrity="sha256-XF29CBwU1MWLaGEnsELogU6Y6rcc5nCkhhx89nFMIDQ=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js" integrity="sha256-CfcERD4Ov4+lKbWbYqXD6aFM9M51gN4GUEtDhkWABMo=" crossorigin="anonymous"></script>
    </body>
</html>

app/views/partials/_navbar.html.erb
<header>

    <nav>
      <div class="row">
        <div class="">
          <ul class="me">
            <li><%=link_to (image_tag("/images/rutan.png" , class:"logo") ),root_path , class:"brand-logo " %></li>
            <li ><%= link_to "Inicio", root_path , class:"text-rutan"%> </li>

          </ul>
        </div>


      </div>

      </nav>



</header>

app/views/welcome/index.html.erb
<br>
<div class="row">
  <div class="col-12 col-md-6">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="/images/tablet.jpg" alt="First slide" class="inicio d-block w-100">

        </div>
        <div class="carousel-item">
          <img src="/images/tablet.jpg" alt="Second slide" class="inicio d-block w-100">
          <img class="d-block w-100" src="..." alt="">
        </div>
        <div class="carousel-item">
          <img src="/images/tablet.jpg" alt="Third slide" class="inicio d-block w-100">
          <img class="d-block w-100" src="..." alt="">
        </div>

      </div>

      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
  </div>

</div>


  <div class="col s12 m6 l6">
    <div class="parrafoInicial">
      <h1 class="text-h">Observatorio  CT+i</h1><br>
      <p class="text-p">
        Propende por el desarrollo de proyectos para el desarrollo políticas
        relacionadas con las tecnologías de la cuarta revolución industrial
      </p>
      <br>


    </div>
  </div>

</div>


 <div class="col s12 m12 l12 text-center">
   <div class="que  valign-wrapper ">
     <div class="container">
       <div class="text-center">
        <h1 class="text-h ">¿Qué es Observatorio  CT+i?</h1>
        <p class="text-p">Es una plataforma tecnologica de Ruta n, que busca brindar información
          relevante a los actores de emprendimiento en la ciudad de Medellin.
        </p>
       </div>

     </div>


     </div>


  </div>



  <div class="container ">
    <h1 class="text-center text-h">Tecnologias</h1>
    <span class="text-p"> Para la vigencia 2019, Colombia eligió trabajar en las siguientes temáticas debido a sus beneficios
      a la vez que se minimizan los riesgos a través de la elaboración de marcos de política pública. </span>
    <div class="row listadoBeneficios ">
      <div class="col-12 col-md-4 col-lg-4  ">

          <img src="/images/ia.png" alt="" class="beneficios center">
          <br>
          <h2 class="tituloBeneficio2">Inteligencia Artificial (IA)</h2>
          <p class="text-p">
            Incorporación de robots al interior de hogares, negocios, manejando
            autos, cuidando jóvenes y ancianos, entre otras prácticas , A través de la
            generación de marcos políticos y protocolos de gobernanza
          </p>
      </div>
      <div class="col-12 col-md-6 col-lg-4 cajonBeneficio">
        <br>
      <img src="/images/bc.png" alt="" class="beneficios">
      <br>
      <h2 class="tituloBeneficio2">Blockchain</h2>
      <p class="text-p">Flujos de trabajo, “tecnología que permite el almacenamiento y transferencia
         de información de manera descentralizada y segura”. Las áreas del proyecto
         incluyen: identidad digital, integración de la cadena de suministro, propiedad
         de datos y sistemas monetarios.
      </p>

      </div>
      <div class="col-12 col-md-6 col-lg-4 cajonBeneficio">
        <br>
      <img src="/images/iot.png" alt="" class="beneficios">
      <br>
      <h2 class="tituloBeneficio2">Internet de las cosas (IoT)</h2>
      <p class="text-p">
        Contempla el incremento que los aparatos tecnológicos conectados a la red.
        Ante tal panorama apremia otorgar más importancia y urgencia al trato de la
        propiedad y seguridad de datos, la seguridad cibernética y la privacidad
      </p>

      </div>
    </div>
  </div>

<div class="container center">
  <h2>ELEMENTOS PRELIMINARES</h2>
  <p>
    La cuarta revolución industrial se ha constituido en el hito más relevante del siglo XXI, por sus efectos transformadores sobre la sociedad en su conjunto. Es una realidad que está cambiando los modelos de relacionamiento empresariales, de los gobiernos y de las personas de una manera profunda y exige de la comprensión de todos los aspectos que involucra, entre otros, el desarrollo de nuevas competencias y habilidades, tecnologías y sistemas, que permitan la adaptación al entorno competitivo que genera. Colombia, al igual que otros países en desarrollo, presenta un rezago en indicadores de productividad y competitividad.
  </p>
  <h4>INFORMES DE INTELIGENCIA GLOBAL</h4>
  <br>
  <div class="row">

        <div class="col-12 col-md-4">
            <%= link_to  "welcome/inteligencia_global_ai" do%>
              <div class="card" style="width: 18rem;">
                <img class="filtro_oscuro card-img-top" src="images/city.jpg " alt="Card image cap">
                <div class="card-body">
                      <h5 class="tituloBeneficio">Informe de inteligencia  global Inteligencia Artificial</h5>
                      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                      <%= link_to 'Mostrar', "welcome/inteligencia_global_ai" ,class:"text-h2 btn coloR" %>
                </div>
              </div>
            <% end %>
      </div>
      <div class="col-12 col-md-4">
          <%= link_to  "welcome/inteligencia_global_blockchain" do%>
            <div class="card" style="width: 18rem;">
              <img class="filtro_oscuro card-img-top" src="images/city.jpg " alt="Card image cap">
              <div class="card-body">
                    <h5 class="tituloBeneficio">Informe de inteligencia global Blockchain</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <%= link_to 'Mostrar', "welcome/blockchain" ,class:"text-h2 btn coloR" %>
              </div>
            </div>
          <% end %>
    </div>
    <div class="col-12 col-md-4">
        <%= link_to  "welcome/inteligencia_global_iot" do%>
          <div class="card" style="width: 18rem;">
            <img class="filtro_oscuro card-img-top" src="images/city.jpg " alt="Card image cap">
            <div class="card-body">
                  <h5 class="tituloBeneficio">Informe de inteligencia global Internet de las Cosas</h5>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <%= link_to 'Mostrar', "welcome/inteligencia_global_iot" ,class:"text-h2 btn coloR" %>

            </div>
          </div>
        <% end %>
  </div>


</div>




</div>
<div class="container">
<h4>INFORMES SECTORIALES</h4>
<br>
  <div class="row center">


    <div class="col-12 col-md-4">
        <%= link_to  "welcome/iot_sectorial" do%>
          <div class="card" style="width: 18rem;">
            <img class="filtro_oscuro card-img-top" src="images/city.jpg " alt="Card image cap">
            <div class="card-body">
                  <h5 class="tituloBeneficio">Informe de inteligencia global Internet de las Cosas</h5>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                  <%= link_to 'Mostrar', "welcome/iot_sectorial" ,class:"text-h2 btn coloR" %>

            </div>
          </div>
        <% end %>
   </div>

   <div class="col-12 col-md-4">
       <%= link_to  "welcome/bc_sectorial" do%>
         <div class="card" style="width: 18rem;">
           <img class="filtro_oscuro card-img-top" src="images/city.jpg " alt="Card image cap">
           <div class="card-body">
                 <h5 class="tituloBeneficio">Informe Sectorial de Blockchain</h5>
                 <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                 <%= link_to 'Mostrar', "welcome/bc_sectorial" ,class:"text-h2 btn coloR" %>
          </div>
         </div>
       <% end %>
  </div>

  <div class="col-12 col-md-4">
      <%= link_to  "welcome/iot_sectorial" do%>
        <div class="card" style="width: 18rem;">
          <img class="filtro_oscuro card-img-top" src="images/city.jpg " alt="Card image cap">
          <div class="card-body">
                <h5 class="tituloBeneficio tituloBeneficio">Informe Sectorial de Internet de las Cosas</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <%= link_to 'Mostrar', "welcome/iot_sectorial" ,class:"text-h2 btn coloR" %>
          </div>
        </div>
      <% end %>
 </div>

  </div>

</div>